name: Make TWRP

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize Build Space
  uses: easimon/maximize-build-space@master
  with:
    root-reserve-mb: 1024
    swap-size-mb: 16384
    remove-dotnet: 'true'
    remove-android: 'true'
    remove-haskell: 'true'
    remove-codeql: 'true'
    - name: Cleanup extra files
  run: |
    sudo rm -rf /usr/local/lib/android
    sudo rm -rf /usr/share/dotnet
    sudo rm -rf /opt/ghc
    sudo apt-get clean
    df -h

- name: Check disk space
  run: |
    df -h
    

  
        - name: Install dependencies
  run: |
    sudo rm -rf /var/lib/apt/lists/*
    sudo apt-get clean
    sudo rm -rf /tmp/*
    sudo apt-get update

        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-core gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk python3 python3-pip

    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Init repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Build-Bot"
        git config --global user.email "build@ci.local"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1

    - name: Repo sync
      run: |
        cd workspace
        repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle 2>&1 || repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle 2>&1 ||

    - name: Clone device tree
      run: |
        cd workspace
        git clone https://github.com/${{ github.repository }}.git -b main ./device/xiaomi/lapis

    - name: Build
      run: |
        cd workspace
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_lapis-eng
        mka vendorbootimage -j$(nproc --all)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lapis_twrp
        path: workspace/out/target/product/lapis/vendor_boot.img
        if-no-files-found: warn
